services:
  nginx:
    image: nginx:alpine
    container_name: noelsdeliveries-client-nginx-app
    ports:
      - 80:80
    volumes:
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/deliveries-app.conf
    depends_on:
      - node
    networks:
      - noelsdeliveries-client

  node:
    build: .
    ports:
      - 3000:80
    volumes:
      - ./:/app
    command: npm run build
    networks:
      - noelsdeliveries-client

  # redis:
  #   image: redis:alpine
  #   networks:
  #     - noelsdeliveries-client

networks:
  noelsdeliveries-client:
    driver: bridge