export const {
    VUE_APP_NAME:APPNAME,
    VUE_APP_URL:APPURL,
    VUE_APP_API_URL:APPAPIBASEURL,
    VITEAPP_SENTRY_DNS:SENTRYDNS,
    VUE_APP_RELEASE:APPRELEASE,
    VUE_APP_MODE:APPMODE,
} = import.meta.env;